In [2]:
import numpy as np
import pandas as pd

###serise from list

In [5]:
country = ["india", "usa", "china", "japan", "germany"]
pd.Series(country)

0      india
1        usa
2      china
3      japan
4    germany
dtype: str

In [ ]:
#integers
runs = [100, 200, 300, 400, 500]
pd.Series(runs)

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [7]:
#custom index
marks = [100, 200, 300, 400, 500]
subjects = ['math','phy','chem','bio','english']
pd.Series(marks, index=subjects)

math       100
phy        200
chem       300
bio        400
english    500
dtype: int64

In [9]:
#setting a name
marks = [100, 200, 300, 400, 500]
subjects = ['math','phy','chem','bio','english']
aji_marks = pd.Series(marks, index=subjects,name='ajinkya ke marks')
aji_marks

math       100
phy        200
chem       300
bio        400
english    500
Name: ajinkya ke marks, dtype: int64

serise from dict

In [13]:
marks = {
    'math':100,
    'phy':200,
    'chem':300,
    'bio':400,
    'english':500
}

aj_marks = pd.Series(marks,name = "ajinkya ke marks")
aj_marks

math       100
phy        200
chem       300
bio        400
english    500
Name: ajinkya ke marks, dtype: int64

series attributes

In [14]:
#size (tells values num)
aj_marks.size

5

In [15]:
#dtype (tells data type of values)
aj_marks.dtype

dtype('int64')

In [ ]:
#names (tells name of series)
aji_marks.name

'ajinkya ke marks'

In [ ]:
#is_unique (tells if values are different or not)
aj_marks.is_unique

True

In [20]:
#index (tells index values)
aj_marks.index

Index(['math', 'phy', 'chem', 'bio', 'english'], dtype='str')

In [21]:
#values (tells values in series)
aj_marks.values

array([100, 200, 300, 400, 500])

series using read_csv

In [4]:
ajdata = pd.read_csv('~/pandas.env/online_shoppers_intention copy.csv')
type(ajdata)

pandas.DataFrame

i am having problem using squeezed function to print data set in series so it is remaining in data frame

#head and tail function

In [6]:
ajdata.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [7]:
ajdata.tail()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

sample

In [8]:
ajdata.sample()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
7805,0,0.0,0,0.0,18,1110.866667,0.0,0.014815,57.035082,0.0,Aug,2,10,4,1,Returning_Visitor,False,True

In [12]:
ajdata.sample(4)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
1505,0,0.0,0,0.0,2,62.00000,0.000000,0.050000,0.0,0.0,Mar,1,1,2,10,Returning_Visitor,False,False
1481,0,0.0,0,0.0,25,1512.52381,0.000000,0.024000,0.0,0.0,Mar,2,2,3,11,Returning_Visitor,False,False
10027,0,0.0,0,0.0,10,80.50000,0.083333,0.092222,0.0,0.0,Dec,2,2,1,3,Returning_Visitor,False,False
7000,0,0.0,0,0.0,4,39.20000,0.000000,0.050000,0.0,0.0,Nov,1,2,1,2,New_Visitor,False,False

value_counts -> 
frequency of value is shown

In [13]:
ajdata.value_counts()

Administrative  Administrative_Duration  Informational  Informational_Duration  ProductRelated  ProductRelated_Duration  BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  Browser  Region  TrafficType  VisitorType        Weekend  Revenue
0               0.0                      0              0.0                     1               0.000000                 0.200000     0.200000   0.000000    0.0         Mar    2                 2        1       1            Returning_Visitor  False    False      14
                                                                                                                                                                                3                 2        3       1            Returning_Visitor  False    False       7
                                                                                                                                                                         May    2                 2        1       3            Returning_Visitor  False    False       7
                                                                                                                                                                                1                 1        1       3            Returning_Visitor  False    False       6
                                                                                                                                                                         Dec    8                 13       9       20           Other              False    False       5
                                                                                                                                                                                                                                                                       ..
3               145.0                    0              0.0                     53              1783.791667              0.007143     0.029031   12.241717   0.0         Dec    4                 6        1       1            Returning_Visitor  True     False       1
0               0.0                      0              0.0                     5               465.750000               0.000000     0.021333   0.000000    0.0         Nov    3                 2        1       8            Returning_Visitor  True     False       1
                                                                                6               184.250000               0.083333     0.086667   0.000000    0.0         Nov    3                 2        1       13           Returning_Visitor  True     False       1
4               75.0                     0              0.0                     15              346.000000               0.000000     0.021053   0.000000    0.0         Nov    2                 2        3       11           Returning_Visitor  False    False       1
0               0.0                      0              0.0                     3               21.250000                0.000000     0.066667   0.000000    0.0         Nov    3                 2        1       2            New_Visitor        True     False       1
Name: count, Length: 12205, dtype: int64

sort_values
ascending is true by default 
 dont change the order in orignal chart

In [ ]:
ajdata.sort_values(by='ProductRelated', ascending=False)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
5152,17,2629.253968,24,2050.433333,705,43171.23338,0.004851,0.015431,0.763829,0.0,May,2,2,1,14,Returning_Visitor,True,False
6684,20,199.456273,7,299.033333,686,23342.08205,0.009853,0.022771,0.150650,0.0,Aug,2,2,1,1,Returning_Visitor,False,False
8308,27,853.735949,2,126.500000,584,24844.15620,0.002099,0.009347,4.511100,0.0,Nov,2,4,3,8,Returning_Visitor,False,False
10318,9,444.284722,0,0.000000,534,18504.12621,0.010857,0.023309,2.547956,0.0,Nov,2,2,3,2,Returning_Visitor,True,True
6787,8,161.668571,0,0.000000,518,11976.72135,0.000038,0.003837,0.000000,0.0,Oct,4,2,9,2,Returning_Visitor,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6935,1,19.600000,0,0.000000,0,0.00000,0.000000,0.088889,0.000000,0.0,Oct,3,5,1,5,Returning_Visitor,False,False
8052,0,0.000000,0,0.000000,0,0.00000,0.200000,0.200000,0.000000,0.0,Nov,1,1,9,2,Returning_Visitor,False,False
4468,1,0.000000,0,0.000000,0,0.00000,0.200000,0.200000,0.000000,0.0,May,2,5,1,2,Returning_Visitor,True,False
3187,0,0.000000,0,0.000000,0,0.00000,0.200000,0.200000,0.000000,0.0,May,2,2,8,3,Returning_Visitor,False,False
11865,0,0.000000,0,0.000000,0,0.00000,0.200000,0.200000,0.000000,0.0,Nov,1,1,8,8,Returning_Visitor,False,False

sorting ordrs permanantly

In [ ]:
ajdata.sort_values(inplace=True, by='ProductRelated', ascending=False)
#but i will not run this code right now beacause it will change the original data and i want to keep it as it is for now.

meathod chaining

In [ ]:
ajdata.sort_values(by='ProductRelated', ascending=False).head().values[0]

array([17, 2629.253968, 24, 2050.433333, 705, 43171.23338, 0.004851285,
       0.015431438, 0.763828956, 0.0, 'May', 2, 2, 1, 14,
       'Returning_Visitor', True, False], dtype=object)

soart_index -> inplace ->

but i dont have index in my data frame right now beacuse i removed it previously

#series math methods

#count-> dont calculate missing values while size alculates missing values(nan values)

In [ ]:
ajdata.count(1) #it will count the number of non null values in each row
ajdata.count(0) #it will count the number of non null values in each column

Administrative             12330
Administrative_Duration    12330
Informational              12330
Informational_Duration     12330
ProductRelated             12330
ProductRelated_Duration    12330
BounceRates                12330
ExitRates                  12330
PageValues                 12330
SpecialDay                 12330
Month                      12330
OperatingSystems           12330
Browser                    12330
Region                     12330
TrafficType                12330
VisitorType                12330
Weekend                    12330
Revenue                    12330
dtype: int64

sum -> product

In [ ]:
ajdata.sum(0) #it will give the sum of each column
ajdata.sum(1) #it will give the sum of each row

/var/folders/_4/g5k20bx92_n735v7h18s2tjr0000gn/T/ipykernel_7610/3796119790.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  ajdata.sum(0)

Administrative                                                         28546
Administrative_Duration                                         996493.46795
Informational                                                           6209
Informational_Duration                                         425044.666449
ProductRelated                                                        391249
ProductRelated_Duration                                      14731220.892216
BounceRates                                                       273.619721
ExitRates                                                         531.087596
PageValues                                                      72614.549447
SpecialDay                                                             757.4
Month                      FebFebFebFebFebFebFebFebFebFebFebFebFebFebFebF...
OperatingSystems                                                       26189
Browser                                                                29063
Region                                                                 38807
TrafficType                                                            50178
VisitorType                Returning_VisitorReturning_VisitorReturning_Vi...
Weekend                                                                 2868
Revenue                                                                 1908
dtype: object

In [ ]:
ajdata['ProductRelated'].prod() #it will give the product of all values in the column 'ProductRelated'
# the o/p will be zero beacuse the number is very large and it will give the product of all values in the column 'ProductRelated' and it will be zero because of overflow error.

np.int64(0)

In [ ]:
ajdata['ProductRelated'].sum() #it will give the sum of all values in the column 'ProductRelated'

np.int64(391249)

#mean -> median -> mode -> standard deviation -> variance -> skewness -> kurtosis

ajdata

In [8]:
ajdata['ProductRelated'].mean() #it will give the mean of all values in the column 'ProductRelated'
ajdata['ProductRelated'].median() #it will give the median of all values in the column 'ProductRelated'
ajdata['ProductRelated'].mode() #it will give the mode of all values in the column 'ProductRelated'
ajdata['ProductRelated'].std() #it will give the standard deviation of all values in the column 'ProductRelated'
ajdata['ProductRelated'].var() #it will give the variance of all values in the column 'ProductRelated'
ajdata['ProductRelated'].min() #it will give the minimum value in the column 'ProductRelated'
ajdata['ProductRelated'].max() #it will give the maximum value in the column 'ProductRelated'

ajdata['ProductRelated'].describe() #it will give the statistical summary of the column '

count    12330.000000
mean        31.731468
std         44.475503
min          0.000000
25%          7.000000
50%         18.000000
75%         38.000000
max        705.000000
Name: ProductRelated, dtype: float64

In [7]:
ajdata.describe() #it will give the statistical summary of all numerical columns in the dataframe

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

50% is the median value in the column 'ProductRelated' and it is 3.0 which means that 50% of the values in the column 'ProductRelated' are less than or equal to 3.0 and 50% of the values are greater than or equal to 3.0.
75% is the third quartile value in the column 'ProductRelated' and it is 5.0 which means that 75% of the values in the column 'ProductRelated' are less than or equal to 5.0 and 25% of the values are greater than or equal to 5.0.

series indexing

In [14]:
#integer indexing
ajdata.iloc[0] #it will give the first row of the dataframe
ajdata.iloc[1] #it will give the second row of the dataframe
ajdata.iloc[0:5] #it will give the first 5 rows of the dataframe
ajdata.iloc[0:5, 0:5] #it will give the first 5 rows and first 5 columns of the dataframe
ajdata.iloc[:, 0:5] #it will give all rows and first 5 columns of the dataframe
ajdata.iloc[0:5, :] #it will give first 5 rows and all columns of the dataframe
ajdata.iloc[3:4, 5:5]

Empty DataFrame
Columns: []
Index: [3]

In [16]:
ajdata.iloc[-3:-4, -5:-5]

Empty DataFrame
Columns: []
Index: []

In [18]:
sample = [2,3,4,5,6]
sample[-4]

3

In [19]:
sample = ['virat','anu','bib','ghf']
sample[-4]

'virat'

#sclicing

In [20]:
# Get entire column as Series
ajdata['ProductRelated']

# Slice first 5 values from a column
ajdata['ProductRelated'][0:5]
ajdata['ProductRelated'].iloc[0:5]

# Slice with step
ajdata['ProductRelated'][::2]  # Every 2nd value

# Using loc (label-based)
ajdata.loc[0:5, 'ProductRelated']

# Using iloc (position-based)
ajdata.iloc[0:5, 0]  # First 5 rows of 1st column

# Multiple columns
ajdata[['ProductRelated', 'Administrative']][0:5]

# Slice with boolean condition
ajdata['ProductRelated'][ajdata['ProductRelated'] > 10]

# Get specific positions
ajdata['ProductRelated'][[0, 2, 4]]  # Values at positions 0, 2, 4

0     1
2     1
4    10
Name: ProductRelated, dtype: int64

In [21]:
#ajdata['ColumnName'][start:end]  # Simple slicing
#ajdata.iloc[start:end, column_index]  # Position-based
#ajdata.loc[start:end, 'ColumnName']  # Label-based

In [22]:
#negative indexing is not supported in pandas series and dataframe. 
# It will give an error if we try to use negative indexing in pandas series and dataframe.

In [ ]:
#fancy indexing 
# is supported in pandas series and dataframe. 
# It allows us to select specific rows and columns from the dataframe using a list of labels or positions.

In [4]:
ajdata['ProductRelated'][[0, 2, 4]]
#This selects the 1st, 3rd and 5th entries from the ProductRelated column.

0     1
2     1
4    10
Name: ProductRelated, dtype: int64

indexing with labels

In [5]:
# label-based indexing using .loc
# access a single value by row label and column name
ajdata.loc[0, 'ProductRelated']

# slice rows by label and select a column
ajdata.loc[0:5, 'ProductRelated']

# select multiple columns for specific row labels
ajdata.loc[0:3, ['ProductRelated', 'Administrative']]

# when index has custom labels, you can use them directly
# e.g. if ajdata.index = ['a','b','c',...], then ajdata.loc['a','ProductRelated']

   ProductRelated  Administrative
0               1               0
1               2               0
2               1               0
3               2               0

#editing series

#coapy and views

series with python functionalities

In [10]:
#len/type/dir/sorted/max/min
print(len(ajdata)) # number of rows in the dataframe
print(type(ajdata)) # type of the object
print(dir(ajdata)) # list of all attributes and methods of the dataframe
print(sorted(ajdata.columns)) # sorted list of column names
print(ajdata['ProductRelated'].max()) # maximum value in the 'ProductRelated'
print(ajdata['ProductRelated'].min()) # minimum value in the 'ProductRelated'

12330
<class 'pandas.DataFrame'>
['Administrative', 'Administrative_Duration', 'BounceRates', 'Browser', 'ExitRates', 'Informational', 'Informational_Duration', 'Month', 'OperatingSystems', 'PageValues', 'ProductRelated', 'ProductRelated_Duration', 'Region', 'Revenue', 'SpecialDay', 'T', 'TrafficType', 'VisitorType', 'Weekend', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
['Administrative', 'Administrative_Duration', 'BounceRates', 'Browser', 'ExitRates', 'Informational', 'Informational_Duration', 'Month', 'OperatingSystems', 'PageValues', 'ProductRelated', 'ProductRelated_Duration', 'Region', 'Revenue', 'SpecialDay', 'TrafficType', 'VisitorType', 'Weekend']
705
0

#type conversion

In [ ]:
list('ProductRelated')

['P', 'r', 'o', 'd', 'u', 'c', 't', 'R', 'e', 'l', 'a', 't', 'e', 'd']

In [15]:
# get the Series…
prod_series = ajdata['ProductRelated']

# …and convert it to a list
prod_list = prod_series.tolist()          # preferred
# or equivalently
prod_list = list(prod_series)

print(type(prod_list))   # <class 'list'>
print(prod_list[:10])    # first ten values, for example

<class 'list'>
[1, 2, 1, 2, 10, 19, 1, 0, 2, 3]

In [16]:
# get the Series…
prod_series = ajdata['ProductRelated']

# …and convert it to a list
prod_list = prod_series.to_dict()          # preferred
# or equivalently
prod_list = dict(prod_series)

print(type(prod_list))   # <class 'dict'>
print(prod_list)         # all key-value pairs, for example

<class 'dict'>

membership operator

to check the particular value is in the series or not

In [17]:
ajdata

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [25]:
'Informational' in ajdata

True

In [ ]:
# Check in a specific column (e.g., ProductRelated)
145.0 in ajdata['ProductRelated'].values

# Count how many times 145.0 appears in that column
(ajdata['ProductRelated'] == 145.0).sum()

# Using isin() method
ajdata['ProductRelated'].isin([145.0]).any()

# Check if 145.0 exists anywhere in the entire dataframe
(ajdata == 145.0).any().any()

np.int64(6)

#looping

In [34]:
for i in ajdata.index[16:20]:
    print(i)

16
17
18
19

In [37]:
for i in ajdata.columns:
    print(f"Checking for 145.0 in column: {i}")
    if (ajdata[i] == 145.0).any():
        print(f"Found 145.0 in column: {i}")

Checking for 145.0 in column: Administrative
Checking for 145.0 in column: Administrative_Duration
Found 145.0 in column: Administrative_Duration
Checking for 145.0 in column: Informational
Checking for 145.0 in column: Informational_Duration
Found 145.0 in column: Informational_Duration
Checking for 145.0 in column: ProductRelated
Found 145.0 in column: ProductRelated
Checking for 145.0 in column: ProductRelated_Duration
Found 145.0 in column: ProductRelated_Duration
Checking for 145.0 in column: BounceRates
Checking for 145.0 in column: ExitRates
Checking for 145.0 in column: PageValues
Checking for 145.0 in column: SpecialDay
Checking for 145.0 in column: Month
Checking for 145.0 in column: OperatingSystems
Checking for 145.0 in column: Browser
Checking for 145.0 in column: Region
Checking for 145.0 in column: TrafficType
Checking for 145.0 in column: VisitorType
Checking for 145.0 in column: Weekend
Checking for 145.0 in column: Revenue

arithemetic operators

In [41]:
100 - ajdata['ProductRelated']

0        99
1        98
2        99
3        98
4        90
         ..
12325    47
12326    95
12327    94
12328    85
12329    97
Name: ProductRelated, Length: 12330, dtype: int64

#relational operators

In [47]:
for i in ajdata[ajdata['ProductRelated'] >= 100]:

    print('hipe')

hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe
hipe

In [48]:
ajdata['ProductRelated'] <= 100

0        True
1        True
2        True
3        True
4        True
         ...
12325    True
12326    True
12327    True
12328    True
12329    True
Name: ProductRelated, Length: 12330, dtype: bool

#boolean indexing on series